export const Colors = {
    PRIMARYPURPLE: "#7B2FF7",
    PRIMARYBLUE: "#00C6FF",
    SKYBLUE: "#4FD3FF",
    BACKGROUND: "#1A1A1A",
    LAVENDERLIGHT: " #D9C2FF",
    SOFTCYAN: "#B9F3FF",
    TEXTDARK: "#1A1A1A",
    DARKGREY: "#4D4D4D",
    LIGHTGREY: "#8C8C8C",
    TEXTMEDIUM: "#4D4D4D",
    TEXTLIGHT: "#8C8C8C",
    WHITE: "#FFFFFF",
    OFFWHITE: "#F7F9FC",
    PRESENT: "#28C76F",
    LATE: "#000000ff",
    ABSENT: "#FF4D4F",
    LEAVE: " #2D9CDB"
}